# Generated by Django 2.2.5 on 2019-10-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='result_image',
            field=models.ImageField(default='default_image.jpg', upload_to='result_image'),
        ),
    ]
