# Generated by Django 2.2.5 on 2019-10-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='gender', max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('patient', 'patient'), ('doctor', 'doctor')], default='usertype', max_length=7),
        ),
    ]
